package com.test;

import com.dto.ConEdRegionInfo;

public class HtmlBuilder2 {

    private String html = "<!DOCTYPE HTML>\n" +
            "\n" +
            "<html>\n" +
            "\n" +
            "<head>\n" +
            "<title></title>\n" +
            "<style type=\"text/css\">\n" +
            "\n" +
            "table{\n" +
            "    border-collapse:collapse;\n" +
            "\n" +
            "}\n" +
            "\n" +
            "\n" +
            "table th{\n" +
            "    padding: 5px 10px;\n" +
            "    background-color: #333333;\n" +
            "    color: #FFFFFF;\n" +
            "    border: #BBBBBB 1px solid;\n" +
            "}\n" +
            "\n" +
            "table td{\n" +
            "    padding: 5px 10px;\n" +
            "    border: #BBBBBB 1px solid;\n" +
            "    color: #0040FF;\n" +
            "    font-size: 12px;\n" +
            "}\n" +
            "\n" +
            "</style>\n" +
            "</head>\n" +
            "\n" +
            "<body>\n" +
            "@REPLACE@"+
            "    <br />\n" +
            "<span style=\"font-size: 11px; color: #222222;\">*email generated by dual fuel automated system</span>" +
            "\n" +
            "</body>\n" +
            "\n" +
            "</html>";

    private String tds = "";

    public void startTable(String city){
        tds = tds + "\n"
                + "<br />\n"
                + "<div style=\"width: 100%; background: #00CCFF; padding: 5px; font-weight: bold; font-size: 16px; border: #0099FF 1px solid;\">"+city+"</div>\n" +
                "<br />\n" +
                "<table>\n" +
                "    <tr>\n" +
                "            <th style=\"padding: 5px 10px;  background-color: #333333; color: #FFFFFF; border: #BBBBBB 1px solid;\">Address</th>\n" +
                "            <th style=\"padding: 5px 10px;  background-color: #333333; color: #FFFFFF; border: #BBBBBB 1px solid;\">Units</th>\n" +
                "            <th style=\"padding: 5px 10px;  background-color: #333333; color: #FFFFFF; border: #BBBBBB 1px solid;\">Primary Fuel</th>\n" +
                "            <th style=\"padding: 5px 10px;  background-color: #333333; color: #FFFFFF; border: #BBBBBB 1px solid;\">Boiler Make</th>\n" +
                "            <th style=\"padding: 5px 10px;  background-color: #333333; color: #FFFFFF; border: #BBBBBB 1px solid;\">Burner Make</th>\n" +
                "            <th style=\"padding: 5px 10px;  background-color: #333333; color: #FFFFFF; border: #BBBBBB 1px solid;\">Map Link</th>\n" +
                "            <th style=\"padding: 5px 10px;  background-color: #333333; color: #FFFFFF; border: #BBBBBB 1px solid;\">Owner Info</th>\n" +
                "    </tr>\n"
                +"";
    }

    public void endTable(){
        tds = tds + "\n" + "</table>\n";
    }

    public void addToTable(String... data) {
        tds = tds + "\n" + "<tr>\n";
        for (String d : data) {
            tds = tds + "            <td style=\"padding: 2px 10px; border: #BBBBBB 1px solid; color: #0040FF; font-size: 12px;  \">" + d + "</td>\n";
        }

        tds = tds + "    </tr>";
    }

    public  String getHtml(){
        return html.replace("@REPLACE@", tds);
    }

}
