package com.test;

import com.dto.ConEdRegion;

public class HtmlBuilder {

    private String html = "<!DOCTYPE HTML>\n" +
            "\n" +
            "<html>\n" +
            "\n" +
            "<head>\n" +
            "<title></title>\n" +
            "<style type=\"text/css\">\n" +
            "\n" +
            "table{\n" +
            "    border-collapse:collapse;\n" +
            "\n" +
            "}\n" +
            "\n" +
            "\n" +
            "table th{\n" +
            "    padding: 5px 10px;\n" +
            "    background-color: #333333;\n" +
            "    color: #FFFFFF;\n" +
            "    border: #BBBBBB 1px solid;\n" +
            "}\n" +
            "\n" +
            "table td{\n" +
            "    padding: 5px 10px;\n" +
            "    border: #BBBBBB 1px solid;\n" +
            "    color: #0040FF;\n" +
            "    font-size: 12px;\n" +
            "}\n" +
            "\n" +
            "</style>\n" +
            "</head>\n" +
            "\n" +
            "<body>\n" +
            "<div style=\"width: 100%; background: #00CCFF; padding: 5px; font-weight: bold; font-size: 16px; border: #0099FF 1px solid;\">Con-Edison Zone @ZONE@</div>\n" +
            "<br />\n" +
            "<table>\n" +
            "    <tr>\n" +
            "            <td style=\"padding: 5px 10px; border: #BBBBBB 1px solid; color: #0000FF; font-size: 14px;  background: #999999; font-weight: bold;\"><span style=\"color: #FF0000\">North -</span> @NORTH@</td>\n" +
            "            <td style=\"padding: 5px 10px; border: #BBBBBB 1px solid; color: #0000FF; font-size: 14px;  background: #999999; font-weight: bold;\"><span style=\"color: #FF0000\">South -</span>  @SOUTH@</td>\n" +
            "            <td style=\"padding: 5px 10px; border: #BBBBBB 1px solid; color: #0000FF; font-size: 14px;  background: #999999; font-weight: bold;\"><span style=\"color: #FF0000\">East -</span>  @EAST@</td>\n" +
            "            <td style=\"padding: 5px 10px; border: #BBBBBB 1px solid; color: #0000FF; font-size: 14px;  background: #999999; font-weight: bold;\"><span style=\"color: #FF0000\">West -</span>  @WEST@</td>\n" +
            "    </tr>\n" +
            "</table>" +
            "<br />\n" +
            "<table>\n" +
            "    <tr>\n" +
            "            <th style=\"padding: 5px 10px;  background-color: #333333; color: #FFFFFF; border: #BBBBBB 1px solid;\">Address</th>\n" +
            "            <th style=\"padding: 5px 10px;  background-color: #333333; color: #FFFFFF; border: #BBBBBB 1px solid;\">Units</th>\n" +
            "            <th style=\"padding: 5px 10px;  background-color: #333333; color: #FFFFFF; border: #BBBBBB 1px solid;\">Primary Fuel</th>\n" +
            "            <th style=\"padding: 5px 10px;  background-color: #333333; color: #FFFFFF; border: #BBBBBB 1px solid;\">Boiler Make</th>\n" +
            "            <th style=\"padding: 5px 10px;  background-color: #333333; color: #FFFFFF; border: #BBBBBB 1px solid;\">Burner Make</th>\n" +
            "            <th style=\"padding: 5px 10px;  background-color: #333333; color: #FFFFFF; border: #BBBBBB 1px solid;\">Map Link</th>\n" +
            "            <th style=\"padding: 5px 10px;  background-color: #333333; color: #FFFFFF; border: #BBBBBB 1px solid;\">Owner Info</th>\n" +
            "    </tr>\n" +
            "    @REPLACE@\n" +
            "</table>\n" +
            "    <br />\n" +
            "<span style=\"font-size: 11px; color: #222222;\">*email generated by dual fuel automated system</span>" +
            "\n" +
            "</body>\n" +
            "\n" +
            "</html>";

    public HtmlBuilder(ConEdRegion detail){
        html = html.replace("@ZONE@", detail.get_ZONE());
        html = html.replace("@NORTH@", detail.get_NORTH());
        html = html.replace("@SOUTH@", detail.get_SOUTH());
        html = html.replace("@EAST@", detail.get_EAST());
        html = html.replace("@WEST@", detail.get_WEST());
    }

    private String tds = "";

    public void addToTable(String... data) {
        tds = tds + "\n" + "<tr>\n";
        for (String d : data) {
            tds = tds + "            <td style=\"padding: 2px 10px; border: #BBBBBB 1px solid; color: #0040FF; font-size: 12px;  \">" + d + "</td>\n";
        }

        tds = tds + "    </tr>";
    }

    public  String getHtml(){
        return html.replace("@REPLACE@", tds);
    }
}
